version: '3'
## Taken from https://raw.githubusercontent.com/swarmpit/swarmpit/1.5/docker-compose.yml with some modifications.

services:
  app:
    image: swarmpit/swarmpit:1.5
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    networks:
      - loggingnet
      - swarmpitnet
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  db:
    image: klaemo/couchdb:2.0.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - loggingnet
      - swarmpitnet
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M

  agent:
    image: swarmpit/agent:2.0
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - loggingnet
      - swarmpitnet
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

networks:
  loggingnet:
    external: 
      name: elk_loggingnet
  swarmpitnet:
    driver: overlay

volumes:
  db-data:
    driver: local

logging: 
  