version: '3'

services: 
  esmain:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - node.name=esmain
      - cluster.name=elk-docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
    volumes:
      - esmain:/usr/share/elasticsearch/data
    networks:
      - loggingnet

  esreplica1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - node.name=esreplica1
      - cluster.name=elk-docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=esmain"
    depends_on: 
      - esmain
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 1024M
        reservations:
          cpus: '0.20'
          memory: 512M
    volumes:
      - esreplica1:/usr/share/elasticsearch/data
    networks:
      - loggingnet

  kibana1:
    image: docker.elastic.co/kibana/kibana:6.4.0
    environment:
      - node.name=kibana1
      - ELASTICSEARCH_URL=http://esmain:9200
    depends_on: 
      - esmain
    networks:
      - loggingnet
    ports:
      - 5601:5601

  logstash1:
    image: docker.elastic.co/logstash/logstash:6.4.0
    environment:
      - node.name=logstash1
      - ELASTICSEARCH_URL=http://esmain:9200
      - xpack.monitoring.enable=true
      - xpack.monitoring.elasticsearch.url=esmain:9200
      - config.string=input { stdin { } beats { port => 5044 } } output { elasticsearch { hosts => ["http://esmain:9200"] } }
    depends_on: 
      - esmain
    networks:
      - loggingnet
    ports:
      - 9600:9600

  beats:
    image: docker.elastic.co/beats/filebeat:6.4.0
    environment:
      - output.logstash.hosts=http://logstash1:5044
      - filebeat.inputs.type=log
      - filebeat.inputs.enabled=true
      - filebeat.inputs.paths=/var/log/*.log*
    depends_on:
      - logstash1
    networks:
      - loggingnet
    deploy:
      mode: global
    volumes:
        - /var/log/*.log*:/var/log/*.log*
    


networks:
  loggingnet:
    driver: overlay

volumes:
  esmain:
    driver: local
  esreplica1:
    driver: local